GET http://localhost:3000/
         
###
POST http://localhost:3000/register
Content-Type: application/json

{
    "userID": "6306021630001@fitm.kmutnb.ac.th",
    "password": "pwd0001",
    "name": "สมชาย กล้ามาก",
    "elec_use":30,
    "roomate":4,
    "Status":false,
    "myroom": 201,
    "image" : ""
}


###
GET http://apiproject.app.ruk-com.cloud

###
POST http://apiproject.app.ruk-com.cloud/register
Content-Type: application/json

{
    "userID": "6306021630017@fitm.kmutnb.ac.th",
    "password": "pwd0017",
    "name": "ออกัส ออสก้า",
    "elec_use":150,
    "roomate":4,
    "Status":false,
    "myroom": 304,
    "image" : "" 
}

